version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: adrien
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U adrien -d mydb"]
      interval: 5s
      timeout: 3s
      retries: 5

  app:
    build: ./app
    container_name: my-python-app
    environment:
      DB_HOST: db
      DB_NAME: mydb
      DB_USER: adrien
      DB_PASS: secret
    depends_on:
      db:
        condition: service_healthy
